'''
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not

Answer: 4613732
'''

import time

def fibonacciSum(n):
	prev = 0
	curr = 1
	value = 0
	while curr <= n:
		next = prev + curr
		prev = curr
		curr = next
		if (curr%2 == 0):
			value += curr
	return value
	
		
if __name__ == "__main__":
	start = time.time()
	result = fibonacciSum(4000000)
	elapsed = (time.time() - start)
	print "result %s returned in %s seconds." % (result,elapsed)

		